# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(674, 491)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(420, 10, 241, 421))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.rbtn_id = QtWidgets.QRadioButton(self.centralwidget)
        self.rbtn_id.setGeometry(QtCore.QRect(250, 10, 82, 17))
        self.rbtn_id.setChecked(True)
        self.rbtn_id.setObjectName("rbtn_id")
        self.rbtn_name = QtWidgets.QRadioButton(self.centralwidget)
        self.rbtn_name.setGeometry(QtCore.QRect(250, 30, 121, 17))
        self.rbtn_name.setObjectName("rbtn_name")
        self.search = QtWidgets.QLineEdit(self.centralwidget)
        self.search.setGeometry(QtCore.QRect(10, 10, 231, 20))
        self.search.setObjectName("search")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(10, 120, 113, 20))
        self.name.setObjectName("name")
        self.tip = QtWidgets.QTextEdit(self.centralwidget)
        self.tip.setEnabled(False)
        self.tip.setGeometry(QtCore.QRect(10, 40, 231, 71))
        self.tip.setObjectName("tip")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 120, 101, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 150, 191, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 180, 261, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 210, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(130, 240, 151, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 270, 91, 16))
        self.label_6.setObjectName("label_6")
        self.roastlevel = QtWidgets.QLineEdit(self.centralwidget)
        self.roastlevel.setGeometry(QtCore.QRect(10, 150, 113, 20))
        self.roastlevel.setObjectName("roastlevel")
        self.condition = QtWidgets.QSpinBox(self.centralwidget)
        self.condition.setGeometry(QtCore.QRect(10, 180, 42, 22))
        self.condition.setMaximum(1)
        self.condition.setObjectName("condition")
        self.price = QtWidgets.QLineEdit(self.centralwidget)
        self.price.setGeometry(QtCore.QRect(10, 210, 113, 20))
        self.price.setObjectName("price")
        self.volume = QtWidgets.QLineEdit(self.centralwidget)
        self.volume.setGeometry(QtCore.QRect(10, 240, 113, 20))
        self.volume.setObjectName("volume")
        self.description = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.description.setGeometry(QtCore.QRect(10, 290, 401, 141))
        self.description.setObjectName("description")
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setEnabled(False)
        self.save.setGeometry(QtCore.QRect(320, 230, 91, 41))
        self.save.setObjectName("save")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.rbtn_id.setText(_translate("MainWindow", "по ID"))
        self.rbtn_name.setText(_translate("MainWindow", "по названию"))
        self.tip.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">Если хотите создать новый, выберите (по ID) и напишите \'0\'.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">Чтобы начать нажмите Enter</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Название"))
        self.label_2.setText(_translate("MainWindow", "Степень прожарки на англ."))
        self.label_3.setText(_translate("MainWindow", "Состояние (в зёрнах (1)/ растворимый (0)"))
        self.label_4.setText(_translate("MainWindow", "Цена(руб.)"))
        self.label_5.setText(_translate("MainWindow", "Объем упаковки(г.)"))
        self.label_6.setText(_translate("MainWindow", "Описание"))
        self.save.setText(_translate("MainWindow", "Сохранить"))
